WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=crc16.o crc64.o
LIB_OBJ?=
TEST_MAIN?=crc_test

include $(WORKSPACE)/mks/sys.mk
include $(WORKSPACE)/mks/final.mk
include $(WORKSPACE)/mks/malloc.mk
include $(WORKSPACE)/mks/latte.mk
include $(WORKSPACE)/mks/info.mk
