LATTE_LIB_WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=crc16xmodem.o crc32c.o
LIB_OBJ?=
TEST_MAIN?=crc_test
MODULE?=crc
LIB_MODULES?=sds
BUILD_INCLUDE=crc.h
include $(LATTE_LIB_WORKSPACE)/mks/sys.mk
include $(LATTE_LIB_WORKSPACE)/mks/final.mk
include $(LATTE_LIB_WORKSPACE)/mks/malloc.mk
include $(LATTE_LIB_WORKSPACE)/mks/latte.mk
include $(LATTE_LIB_WORKSPACE)/mks/info.mk
include $(LATTE_LIB_WORKSPACE)/src/sds/lib.mk