LATTE_LIB_WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=mutex.o 
LIB_OBJ?= 
TEST_MAIN?=mutex_test
MODULE?=mutex
LIB_MODULES?=zmalloc
BUILD_INCLUDE=mutex.h

include $(LATTE_LIB_WORKSPACE)/mks/sys.mk
include $(LATTE_LIB_WORKSPACE)/mks/final.mk
include $(LATTE_LIB_WORKSPACE)/mks/malloc.mk
include $(LATTE_LIB_WORKSPACE)/mks/latte.mk
include $(LATTE_LIB_WORKSPACE)/mks/info.mk
include $(LATTE_LIB_WORKSPACE)/src/zmalloc/lib.mk