LATTE_LIB_WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=thread_job.o thread_consumer_job.o
LIB_OBJ?=
TEST_MAIN?=thread_job_test
LIB_MODULES?=
MODULE?=thread_job
BUILD_INCLUDE=thread_job.h thread_consumer_job.h

include $(LATTE_LIB_WORKSPACE)/mks/sys.mk
include $(LATTE_LIB_WORKSPACE)/mks/final.mk
include $(LATTE_LIB_WORKSPACE)/mks/malloc.mk
include $(LATTE_LIB_WORKSPACE)/mks/latte.mk
include $(LATTE_LIB_WORKSPACE)/mks/info.mk
include $(LATTE_LIB_WORKSPACE)/src/thread_pool/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/utils/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/log/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/list/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/vector/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/time/lib.mk
