WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=object.o string.o
LIB_OBJ?=
TEST_MAIN?=object_test

include $(WORKSPACE)/mks/sys.mk
include $(WORKSPACE)/mks/final.mk
include $(WORKSPACE)/mks/malloc.mk
include $(WORKSPACE)/mks/latte.mk
include $(WORKSPACE)/mks/info.mk
include $(WORKSPACE)/src/zmalloc/lib.mk
include $(WORKSPACE)/src/list/lib.mk
include $(WORKSPACE)/src/sds/lib.mk
include $(WORKSPACE)/src/ae/lib.mk