WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=ae.o monotonic.o
LIB_OBJ?=
TEST_MAIN?=ae_test

include $(WORKSPACE)/mks/sys.mk
include $(WORKSPACE)/mks/final.mk
include $(WORKSPACE)/mks/malloc.mk
include $(WORKSPACE)/mks/latte.mk
include $(WORKSPACE)/mks/info.mk
include $(WORKSPACE)/src/zmalloc/lib.mk
include $(WORKSPACE)/src/anet/lib.mk