bio.o: bio.c bio.h latte_c.h libs/ae.h libs/dict.h libs/siphash.h \
  libs/connection.h libs/sds.h libs/zmalloc.h libs/adlist.h libs/log.h \
  libs/utils.h
config.o: config.c latte_c.h libs/ae.h libs/dict.h libs/siphash.h \
  libs/connection.h libs/sds.h libs/zmalloc.h libs/log.h libs/utils.h
latte_c.o: latte_c.c latte_c.h libs/ae.h libs/dict.h libs/siphash.h \
  libs/connection.h libs/sds.h libs/zmalloc.h setproctitle.h config.h \
  libs/utils.h module.h libs/adlist.h
latte_c1.o: latte_c1.c libs/sds.h libs/zmalloc.h libs/utils.h libs/dict.h \
  libs/siphash.h libs/connection.h libs/ae.h libs/syncio.h libs/anet.h \
  libs/latteServer.h
latte_c2.o: latte_c2.c latte_c.h libs/ae.h libs/dict.h libs/siphash.h \
  libs/connection.h libs/sds.h libs/zmalloc.h libs/atomicvar.h \
  libs/latteassert.h libs/utils.h libs/syncio.h libs/anet.h \
  libs/latteServer.h libs/log.h libs/rax.h
module.o: module.c module.h libs/dict.h libs/siphash.h libs/adlist.h \
  libs/dict_plus.h libs/sds.h libs/zmalloc.h
replication.o: replication.c replication.h libs/connection.h libs/sds.h \
  libs/zmalloc.h libs/ae.h latte_c.h libs/dict.h libs/siphash.h \
  libs/log.h libs/utils.h
setproctitle.o: setproctitle.c setproctitle.h
