WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=anet.o
LIB_OBJ?=
TEST_MAIN?=anet_test
MODULE?=anet
BUILD_INCLUDE?=anet.h
LIB_MODULES?=zmalloc

include $(WORKSPACE)/mks/sys.mk
include $(WORKSPACE)/mks/final.mk
include $(WORKSPACE)/mks/malloc.mk
include $(WORKSPACE)/mks/latte.mk
include $(WORKSPACE)/mks/info.mk
include $(WORKSPACE)/src/zmalloc/lib.mk
