WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=anet.o
LIB_OBJ?=
TEST_MAIN?=anet_test

include $(WORKSPACE)/mks/sys.mk
include $(WORKSPACE)/mks/final.mk
include $(WORKSPACE)/mks/malloc.mk
include $(WORKSPACE)/mks/latte.mk
include $(WORKSPACE)/mks/info.mk
include $(WORKSPACE)/src/zmalloc/lib.mk
