LATTE_LIB_WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=latte_debug.o 
TEST_MAIN?=latte_debug_test
MODULE?=debug
LIB_MODULES?=
BUILD_INCLUDE=latte_debug.h 
include $(LATTE_LIB_WORKSPACE)/mks/sys.mk
include $(LATTE_LIB_WORKSPACE)/mks/final.mk
include $(LATTE_LIB_WORKSPACE)/mks/malloc.mk
include $(LATTE_LIB_WORKSPACE)/mks/latte.mk
include $(LATTE_LIB_WORKSPACE)/mks/info.mk
