WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=avl_tree.o b_plus_tree.o
LIB_OBJ?=
TEST_MAIN?=tree_test
LIB_MODULES?=zmalloc iterator utils log vector
MODULE?=tree
BUILD_INCLUDE=avl_tree.h b_plus_tree.h

include $(WORKSPACE)/mks/sys.mk
include $(WORKSPACE)/mks/final.mk
include $(WORKSPACE)/mks/malloc.mk
include $(WORKSPACE)/mks/latte.mk
include $(WORKSPACE)/mks/info.mk
include $(WORKSPACE)/src/zmalloc/lib.mk
include $(WORKSPACE)/src/iterator/lib.mk
include $(WORKSPACE)/src/utils/lib.mk
include $(WORKSPACE)/src/log/lib.mk
include $(WORKSPACE)/src/vector/lib.mk




