WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=avlTree.o
LIB_OBJ?=
TEST_MAIN?=tree_test
LIB_MODULES?=zmalloc iterator
MODULE?=tree
BUILD_INCLUDE=avlTree.h

include $(WORKSPACE)/mks/sys.mk
include $(WORKSPACE)/mks/final.mk
include $(WORKSPACE)/mks/malloc.mk
include $(WORKSPACE)/mks/latte.mk
include $(WORKSPACE)/mks/info.mk
include $(WORKSPACE)/src/zmalloc/lib.mk
include $(WORKSPACE)/src/iterator/lib.mk





