LATTE_LIB_WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=queue.o 
LIB_OBJ?= 
TEST_MAIN?=queue_test
MODULE?=queue
BUILD_INCLUDE=queue.h

include $(LATTE_LIB_WORKSPACE)/mks/sys.mk
include $(LATTE_LIB_WORKSPACE)/mks/final.mk
include $(LATTE_LIB_WORKSPACE)/mks/malloc.mk

include $(LATTE_LIB_WORKSPACE)/mks/info.mk

include $(LATTE_LIB_WORKSPACE)/src/os/lib.mk

include $(LATTE_LIB_WORKSPACE)/mks/latte.mk

