LATTE_LIB_WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=localtime.o
LIB_OBJ?=
TEST_MAIN?=localtime_test
LIB_MODULES?=
MODULE?=time
BUILD_INCLUDE=localtime.h

include $(LATTE_LIB_WORKSPACE)/mks/sys.mk
include $(LATTE_LIB_WORKSPACE)/mks/final.mk
include $(LATTE_LIB_WORKSPACE)/mks/malloc.mk
include $(LATTE_LIB_WORKSPACE)/mks/latte.mk
include $(LATTE_LIB_WORKSPACE)/mks/info.mk
