WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=skiplist.o 
LIB_OBJ?=
TEST_MAIN?=skiplist_test
LIB_MODULES?=zmalloc
MODULE?=skiplist
BUILD_INCLUDE=skiplist.h

include $(WORKSPACE)/mks/sys.mk
include $(WORKSPACE)/mks/final.mk
include $(WORKSPACE)/mks/malloc.mk
include $(WORKSPACE)/mks/latte.mk
include $(WORKSPACE)/mks/info.mk
include $(WORKSPACE)/src/zmalloc/lib.mk
include $(WORKSPACE)/src/sds/lib.mk



