LATTE_LIB_WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=async.o
LIB_OBJ?=
TEST_MAIN?=async_test
MODULE?=async
BUILD_INCLUDE?=async.h 
LIB_MODULES?=zmalloc task dict sds


include $(LATTE_LIB_WORKSPACE)/mks/sys.mk
include $(LATTE_LIB_WORKSPACE)/mks/final.mk
include $(LATTE_LIB_WORKSPACE)/mks/malloc.mk
include $(LATTE_LIB_WORKSPACE)/mks/latte.mk
include $(LATTE_LIB_WORKSPACE)/mks/info.mk
include $(LATTE_LIB_WORKSPACE)/src/zmalloc/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/task/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/dict/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/sds/lib.mk