WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=endianconv.o 
LIB_OBJ?=
TEST_MAIN?=endianconv_test
MODULE?=endianconv
BUILD_INCLUDE=endianconv.h

include $(WORKSPACE)/mks/sys.mk
include $(WORKSPACE)/mks/final.mk
include $(WORKSPACE)/mks/malloc.mk
include $(WORKSPACE)/mks/latte.mk
include $(WORKSPACE)/mks/info.mk
include $(WORKSPACE)/src/utils/lib.mk

