LATTE_LIB_WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=endianconv.o 
LIB_OBJ?=
TEST_MAIN?=endianconv_test
MODULE?=endianconv
BUILD_INCLUDE=endianconv.h

include $(LATTE_LIB_WORKSPACE)/mks/sys.mk
include $(LATTE_LIB_WORKSPACE)/mks/final.mk
include $(LATTE_LIB_WORKSPACE)/mks/malloc.mk
include $(LATTE_LIB_WORKSPACE)/mks/latte.mk
include $(LATTE_LIB_WORKSPACE)/mks/info.mk
include $(LATTE_LIB_WORKSPACE)/src/utils/lib.mk

