WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=ror.o 
LIB_OBJ?= 
TEST_MAIN?=ror_test

include $(WORKSPACE)/mks/sys.mk
include $(WORKSPACE)/mks/final.mk
include $(WORKSPACE)/mks/malloc.mk

include $(WORKSPACE)/mks/info.mk
include $(WORKSPACE)/src/zmalloc/lib.mk
include $(WORKSPACE)/src/sds/lib.mk
include $(WORKSPACE)/src/utils/lib.mk
include $(WORKSPACE)/mks/latte.mk