LATTE_LIB_WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=async_io.o
TEST_MAIN?=async_io_test
BUILD_INCLUDE?=async_io.h
MODULE?=async_io 

include $(LATTE_LIB_WORKSPACE)/mks/sys.mk
include $(LATTE_LIB_WORKSPACE)/mks/final.mk
include $(LATTE_LIB_WORKSPACE)/mks/malloc.mk
include $(LATTE_LIB_WORKSPACE)/mks/latte.mk
include $(LATTE_LIB_WORKSPACE)/mks/info.mk
include $(LATTE_LIB_WORKSPACE)/src/zmalloc/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/sds/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/log/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/debug/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/thread_single_object/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/utils/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/error/lib.mk
include $(LATTE_LIB_WORKSPACE)/mks/sys_config.mk
#test include
include $(LATTE_LIB_WORKSPACE)/src/ae/lib.mk