LATTE_LIB_WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=siphash.o 
LIB_OBJ?=
TEST_MAIN?=siphash_test
LIB_MODULES?=zmalloc
MODULE?=siphash
BUILD_INCLUDE=siphash.h

include $(LATTE_LIB_WORKSPACE)/mks/sys.mk
include $(LATTE_LIB_WORKSPACE)/mks/final.mk
include $(LATTE_LIB_WORKSPACE)/mks/malloc.mk
include $(LATTE_LIB_WORKSPACE)/mks/latte.mk
include $(LATTE_LIB_WORKSPACE)/mks/info.mk
include $(LATTE_LIB_WORKSPACE)/src/zmalloc/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/sds/lib.mk

