LATTE_LIB_WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=iterator.o
LIB_OBJ?=
TEST_MAIN?=iterator_test
LIB_MODULES?=zmalloc
MODULE?=iterator
BUILD_INCLUDE=iterator.h

include $(LATTE_LIB_WORKSPACE)/mks/sys.mk
include $(LATTE_LIB_WORKSPACE)/mks/final.mk
include $(LATTE_LIB_WORKSPACE)/mks/malloc.mk
include $(LATTE_LIB_WORKSPACE)/mks/latte.mk
include $(LATTE_LIB_WORKSPACE)/mks/info.mk
include $(LATTE_LIB_WORKSPACE)/src/zmalloc/lib.mk
