
LATTE_LIB_WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=zset.o 
TEST_MAIN?=zset_test
BUILD_INCLUDE?=zset.h 
MODULE?=zset 
LIB_MODULES?=utils zmalloc sds dict


include $(LATTE_LIB_WORKSPACE)/mks/sys.mk
include $(LATTE_LIB_WORKSPACE)/mks/final.mk
include $(LATTE_LIB_WORKSPACE)/mks/malloc.mk
include $(LATTE_LIB_WORKSPACE)/mks/latte.mk
include $(LATTE_LIB_WORKSPACE)/mks/info.mk
include $(LATTE_LIB_WORKSPACE)/src/zmalloc/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/sds/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/dict/lib.mk





