
WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=zmalloc.o 
TEST_MAIN?=zmalloc_test
BUILD_INCLUDE?=zmalloc.h solarisfixes.h
MODULE?=zmalloc 
LIB_MODULES?=utils


include $(WORKSPACE)/mks/sys.mk
include $(WORKSPACE)/mks/final.mk
include $(WORKSPACE)/mks/malloc.mk
include $(WORKSPACE)/mks/latte.mk
include $(WORKSPACE)/mks/info.mk





