LATTE_LIB_WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=thread_single_object.o
LIB_OBJ?=
TEST_MAIN?=thread_single_object_test
LIB_MODULES?=zmalloc sds dict debug log
MODULE?=thread_single_object
BUILD_INCLUDE=thread_single_object.h

include $(LATTE_LIB_WORKSPACE)/mks/sys.mk
include $(LATTE_LIB_WORKSPACE)/mks/final.mk
include $(LATTE_LIB_WORKSPACE)/mks/malloc.mk
include $(LATTE_LIB_WORKSPACE)/mks/latte.mk
include $(LATTE_LIB_WORKSPACE)/mks/info.mk
include $(LATTE_LIB_WORKSPACE)/src/zmalloc/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/sds/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/dict/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/debug/lib.mk 
include $(LATTE_LIB_WORKSPACE)/src/log/lib.mk


