LATTE_LIB_WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=func_task.o
LIB_OBJ?=
TEST_MAIN?=func_task_test
MODULE?=func_task
BUILD_INCLUDE?= func_task.h
LIB_MODULES?=zmalloc dict log

include $(LATTE_LIB_WORKSPACE)/mks/sys.mk
include $(LATTE_LIB_WORKSPACE)/mks/final.mk
include $(LATTE_LIB_WORKSPACE)/mks/malloc.mk
include $(LATTE_LIB_WORKSPACE)/mks/latte.mk
include $(LATTE_LIB_WORKSPACE)/mks/info.mk
include $(LATTE_LIB_WORKSPACE)/src/zmalloc/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/log/lib.mk
