LATTE_LIB_WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=rax.o
LIB_OBJ?=
TEST_MAIN?=rax_test
LIB_MODULES?=zmalloc
MODULE?=rax
BUILD_INCLUDE=rax.h

include $(LATTE_LIB_WORKSPACE)/mks/sys.mk
include $(LATTE_LIB_WORKSPACE)/mks/final.mk
include $(LATTE_LIB_WORKSPACE)/mks/malloc.mk
include $(LATTE_LIB_WORKSPACE)/mks/latte.mk
include $(LATTE_LIB_WORKSPACE)/mks/info.mk
include $(LATTE_LIB_WORKSPACE)/src/zmalloc/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/utils/lib.mk
