WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?= error.o
LIB_OBJ?=
TEST_MAIN?=error_test
LIB_MODULES?=
MODULE?=error
BUILD_INCLUDE=error.h

include $(WORKSPACE)/mks/sys.mk
include $(WORKSPACE)/mks/final.mk
include $(WORKSPACE)/mks/malloc.mk
include $(WORKSPACE)/mks/latte.mk
include $(WORKSPACE)/mks/info.mk

include $(WORKSPACE)/src/zmalloc/lib.mk
include $(WORKSPACE)/src/sds/lib.mk




