LATTE_LIB_WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=log.o
LIB_OBJ?=
TEST_MAIN?=log_test
LIB_MODULES?=zmalloc sds dict utils 
MODULE?=log
BUILD_INCLUDE=log.h

include $(LATTE_LIB_WORKSPACE)/mks/sys.mk
include $(LATTE_LIB_WORKSPACE)/mks/final.mk
include $(LATTE_LIB_WORKSPACE)/mks/malloc.mk
include $(LATTE_LIB_WORKSPACE)/mks/latte.mk
include $(LATTE_LIB_WORKSPACE)/mks/info.mk
include $(LATTE_LIB_WORKSPACE)/src/zmalloc/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/sds/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/utils/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/dict/lib.mk
