WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=vector.o 
TEST_MAIN?=vector_test
LIB_MODULES?=zmalloc utils log iterator
BUILD_INCLUDE?=vector.h 
MODULE?=vector 

include $(WORKSPACE)/mks/sys.mk
include $(WORKSPACE)/mks/final.mk
include $(WORKSPACE)/mks/malloc.mk
include $(WORKSPACE)/mks/latte.mk
include $(WORKSPACE)/mks/info.mk
include $(WORKSPACE)/src/zmalloc/lib.mk
include $(WORKSPACE)/src/log/lib.mk
include $(WORKSPACE)/src/iterator/lib.mk