LATTE_LIB_WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=vector.o 
TEST_MAIN?=vector_test
LIB_MODULES?=zmalloc utils log iterator cmp
BUILD_INCLUDE?=vector.h 
MODULE?=vector 

include $(LATTE_LIB_WORKSPACE)/mks/sys.mk
include $(LATTE_LIB_WORKSPACE)/mks/final.mk
include $(LATTE_LIB_WORKSPACE)/mks/malloc.mk
include $(LATTE_LIB_WORKSPACE)/mks/latte.mk
include $(LATTE_LIB_WORKSPACE)/mks/info.mk
include $(LATTE_LIB_WORKSPACE)/src/zmalloc/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/log/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/iterator/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/cmp/lib.mk