WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=cmp.o
LIB_OBJ?=
TEST_MAIN?=cmp_test
MODULE?=cmp
BUILD_INCLUDE=cmp.h
LIB_MODULES?=
include $(WORKSPACE)/mks/sys.mk
include $(WORKSPACE)/mks/final.mk
include $(WORKSPACE)/mks/malloc.mk
include $(WORKSPACE)/mks/latte.mk
include $(WORKSPACE)/mks/info.mk
# echo $(foreach module,$(LIB_MODULES),$(WORKSPACE)/src/$(module)/lib.mk)


