LATTE_LIB_WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=cmp.o
LIB_OBJ?=
TEST_MAIN?=cmp_test
MODULE?=cmp
BUILD_INCLUDE=cmp.h
LIB_MODULES?=
include $(LATTE_LIB_WORKSPACE)/mks/sys.mk
include $(LATTE_LIB_WORKSPACE)/mks/final.mk
include $(LATTE_LIB_WORKSPACE)/mks/malloc.mk
include $(LATTE_LIB_WORKSPACE)/mks/latte.mk
include $(LATTE_LIB_WORKSPACE)/mks/info.mk
# echo $(foreach module,$(LIB_MODULES),$(LATTE_LIB_WORKSPACE)/src/$(module)/lib.mk)


