WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=dict_plugins.o 
LIB_OBJ?=
TEST_MAIN?=dict_plugins_test
MODULE?=dict_plugins
BUILD_INCLUDE=dict_plugins.h
LIB_MODULES?=dict
include $(WORKSPACE)/mks/sys.mk
include $(WORKSPACE)/mks/final.mk
include $(WORKSPACE)/mks/malloc.mk
include $(WORKSPACE)/mks/latte.mk
include $(WORKSPACE)/mks/info.mk
include $(WORKSPACE)/src/zmalloc/lib.mk