WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=thread_pool.o
LIB_OBJ?=
TEST_MAIN?=thread_pool_test
LIB_MODULES?=zmalloc iterator utils log vector list anet ae mutex
MODULE?=tree
BUILD_INCLUDE=thread_pool.h

include $(WORKSPACE)/mks/sys.mk
include $(WORKSPACE)/mks/final.mk
include $(WORKSPACE)/mks/malloc.mk
include $(WORKSPACE)/mks/latte.mk
include $(WORKSPACE)/mks/info.mk
include $(WORKSPACE)/src/zmalloc/lib.mk
include $(WORKSPACE)/src/iterator/lib.mk
include $(WORKSPACE)/src/utils/lib.mk
include $(WORKSPACE)/src/log/lib.mk
include $(WORKSPACE)/src/vector/lib.mk
include $(WORKSPACE)/src/ae/lib.mk
include $(WORKSPACE)/src/list/lib.mk
include $(WORKSPACE)/src/mutex/lib.mk




