
LATTE_LIB_WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=thread_pool.o 
TEST_MAIN?=thread_pool_test
BUILD_INCLUDE?=thread_pool.h 
MODULE?=thread_pool 
LIB_MODULES?=utils


include $(LATTE_LIB_WORKSPACE)/mks/sys.mk
include $(LATTE_LIB_WORKSPACE)/mks/final.mk
include $(LATTE_LIB_WORKSPACE)/mks/malloc.mk
include $(LATTE_LIB_WORKSPACE)/mks/latte.mk
include $(LATTE_LIB_WORKSPACE)/mks/info.mk
include $(LATTE_LIB_WORKSPACE)/src/zmalloc/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/utils/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/log/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/list/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/vector/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/time/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/utils/lib.mk







