WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=list.o latte_list.o
LIB_OBJ?=
TEST_MAIN?=latte_list_test

include $(WORKSPACE)/mks/sys.mk
include $(WORKSPACE)/mks/final.mk
include $(WORKSPACE)/mks/malloc.mk
include $(WORKSPACE)/mks/latte.mk
include $(WORKSPACE)/mks/info.mk
include $(WORKSPACE)/src/zmalloc/lib.mk
include $(WORKSPACE)/src/sds/lib.mk

