WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=coding.o 
LIB_OBJ?=../sds/sds.o
TEST_MAIN?=coding_test

include $(WORKSPACE)/mks/sys.mk
include $(WORKSPACE)/mks/final.mk
include $(WORKSPACE)/mks/malloc.mk
include $(WORKSPACE)/mks/latte.mk
include $(WORKSPACE)/mks/info.mk
include $(WORKSPACE)/src/sds/lib.mk


