WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=list.o
LIB_OBJ?=
TEST_MAIN?=list_test
LIB_MODULES?=zmalloc iterator
MODULE?=list
BUILD_INCLUDE=list.h

include $(WORKSPACE)/mks/sys.mk
include $(WORKSPACE)/mks/final.mk
include $(WORKSPACE)/mks/malloc.mk
include $(WORKSPACE)/mks/latte.mk
include $(WORKSPACE)/mks/info.mk
include $(WORKSPACE)/src/zmalloc/lib.mk
include $(WORKSPACE)/src/sds/lib.mk
include $(WORKSPACE)/src/iterator/lib.mk