WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=sds.o 
LIB_OBJ?=../zmalloc/zmalloc.o
TEST_MAIN?=sds_test

include $(WORKSPACE)/mks/sys.mk
include $(WORKSPACE)/mks/final.mk
include $(WORKSPACE)/mks/malloc.mk
include $(WORKSPACE)/mks/latte.mk
include $(WORKSPACE)/mks/info.mk
include $(WORKSPACE)/src/zmalloc/lib.mk


