LATTE_LIB_WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=sds.o sds_plugins.o
LIB_OBJ?=
TEST_MAIN?=sds_test
LIB_MODULES?=zmalloc
MODULE?=sds
BUILD_INCLUDE=sds.h sds_plugins.h

include $(LATTE_LIB_WORKSPACE)/mks/sys.mk
include $(LATTE_LIB_WORKSPACE)/mks/final.mk
include $(LATTE_LIB_WORKSPACE)/mks/malloc.mk
include $(LATTE_LIB_WORKSPACE)/mks/latte.mk
include $(LATTE_LIB_WORKSPACE)/mks/info.mk
include $(LATTE_LIB_WORKSPACE)/src/zmalloc/lib.mk



