LATTE_LIB_WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=listpack.o
LIB_OBJ?=
TEST_MAIN?=listpack_test
LIB_MODULES?=zmalloc sds dict utils time
MODULE?=listpack
BUILD_INCLUDE=listpack.h

include $(LATTE_LIB_WORKSPACE)/mks/sys.mk
include $(LATTE_LIB_WORKSPACE)/mks/final.mk
include $(LATTE_LIB_WORKSPACE)/mks/malloc.mk
include $(LATTE_LIB_WORKSPACE)/mks/latte.mk
include $(LATTE_LIB_WORKSPACE)/mks/info.mk
include $(LATTE_LIB_WORKSPACE)/src/zmalloc/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/log/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/utils/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/debug/lib.mk