LATTE_LIB_WORKSPACE?=$(CURDIR)/../..
BUILD_OBJ?=value.o
LIB_OBJ?=
TEST_MAIN?=value_test
LIB_MODULES?=zmalloc sds iterator dict vector utils log
MODULE?=value
BUILD_INCLUDE=value.h

include $(LATTE_LIB_WORKSPACE)/mks/sys.mk
include $(LATTE_LIB_WORKSPACE)/mks/final.mk
include $(LATTE_LIB_WORKSPACE)/mks/malloc.mk
include $(LATTE_LIB_WORKSPACE)/mks/latte.mk
include $(LATTE_LIB_WORKSPACE)/mks/info.mk
include $(LATTE_LIB_WORKSPACE)/src/zmalloc/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/sds/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/dict/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/vector/lib.mk
include $(LATTE_LIB_WORKSPACE)/src/iterator/lib.mk